core:
  - graphgen/**/*

examples:
  - examples/**/*

baselines:
  - baselines/**/*

documentation:
  - "**/*.md"

workflows:
  - .github/workflows/*.yml
  - .github/workflows/*.yaml

config:
  - .github/labeler.yml
  - .pre-commit-config.yaml
  - .pylintrc
